version: '2'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
     - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      SA_PASSWORD: <my_sa_password>
      MSSQL_AGENT_ENABLED: "true"
  zookeeper:
    image: "debezium/zookeeper:1.6"
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: "debezium/kafka:1.6"
    ports:
     - 9092:9092
     - 29094:29094
    links:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://kafka:9092,LISTENER_ALICE://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092,LISTENER_ALICE://<your_computer_dns_name>:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
  connect:
    image: "debezium/connect:1.6"
    ports:
     - 8083:8083
    links:
      - zookeeper
      - kafka
      - sqlserver
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses